/* Which brand are we selling the most this year? */
SELECT BRAND_NAME, COUNT(BRAND_NAME) AS PHONES_SOLD, YEAR(TIME_S) 
FROM BRANDS, PRODUCT, PRICE, CURRENCY, TICKET 
WHERE BRANDS.BRAND_ID = PRODUCT.BRAND_ID 
AND PRODUCT.PRODUCT_ID = PRICE.PRODUCT_ID 
AND CURRENCY.CURRENCY_ID = PRICE.COST_CURRENCY 
AND TICKET.CURRENCY_ID = CURRENCY.CURRENCY_ID 
AND YEAR(TIME_S) = '2021' 
GROUP BY BRAND_NAME 
ORDER BY COUNT(BRAND_NAME) DESC LIMIT 1