/* Show the revenue per type of credit card. */
SELECT CARD_TYPE, SUM(TOTAL_ORDER) AS REVENUE
FROM TICKET, PAYMENTS, CARD_OR_OTHER, CREDIT_CARD, CARD 
WHERE TICKET.PAYMENT_ID = PAYMENTS.PAYMENT_ID 
AND PAYMENTS.PAYMENT_TYPE = CARD_OR_OTHER.PAYMENT_TYPE 
AND CARD_OR_OTHER.PAYMENT_TYPE = CREDIT_CARD.PAYMENT_TYPE 
AND CREDIT_CARD_ID = CARD.CARD_ID 
GROUP BY CARD_TYPE