/* Which are the top 3 phone sales? */
SELECT PRODUCT.DESCRIPTION, COUNT(PRODUCT.DESCRIPTION) 
FROM PRODUCT, PRICE, CURRENCY, TICKET 
WHERE PRODUCT.PRODUCT_ID = PRICE.PRODUCT_ID 
AND CURRENCY.CURRENCY_ID = PRICE.COST_CURRENCY 
AND TICKET.CURRENCY_ID = CURRENCY.CURRENCY_ID 
GROUP BY PRODUCT.DESCRIPTION 
ORDER BY COUNT(PRODUCT.DESCRIPTION) DESC LIMIT 3

 