/* Who (salesman) makes us earn more money? */
SELECT SALESMAN.SALESMAN_ID, NAME, LAST_NAME, SUM(TOTAL_ORDER) 
FROM SALESMAN, TICKET 
WHERE SALESMAN.SALESMAN_ID = TICKET.SALESMAN_ID  
GROUP BY SALESMAN.SALESMAN_ID
HAVING SUM(TOTAL_ORDER) >= ALL (SELECT SUM(TOTAL_ORDER) 
FROM SALESMAN, TICKET 
WHERE SALESMAN.SALESMAN_ID = TICKET.SALESMAN_ID
GROUP BY SALESMAN.SALESMAN_ID)