/* Show the Specs of the 3 most sold Phones */
SELECT PRODUCT.DESCRIPTION, STORAGE.VALUE AS STORAGE_TB, RAM.VALUE AS RAM_GB, CAMERA.DESCRIPTION AS CAMERA, SIM.DESCRIPTION AS SIM_TYPE, PROCESSOR.DESCRIPTION AS PROCESSOR, COUNT(PRODUCT.DESCRIPTION) AS PHONES_SOLD
FROM STORAGE, RAM, CAMERA, SIM, PROCESSOR, PRODUCT, PRICE, CURRENCY, TICKET
WHERE STORAGE.STORAGE_ID = PRODUCT.STORAGE_ID
AND RAM.RAM_ID = PRODUCT.RAM_ID
AND CAMERA.CAMERA_ID = PRODUCT.CAMERA_ID
AND SIM.SIM_ID = PRODUCT.SIM_ID
AND PROCESSOR.PROCESSOR_ID = PRODUCT.PROCESSOR_ID
AND PRODUCT.PRODUCT_ID = PRICE.PRODUCT_ID 
AND CURRENCY.CURRENCY_ID = PRICE.COST_CURRENCY 
AND TICKET.CURRENCY_ID = CURRENCY.CURRENCY_ID
GROUP BY PRODUCT.DESCRIPTION 
ORDER BY COUNT(PRODUCT.DESCRIPTION) DESC LIMIT 3